### ISSUE TITLE
No Output files generated

### ISSUE THREAD

**Issue by Sandeep-Malhotra** [eddeee888/graphql-code-generator-plugins#74] opened 2023-02-13 00:53 UTC
I am following the steps as described [here](https://the-guild.dev/graphql/codegen/docs/guides/graphql-server-apollo-yoga-with-server-preset)

Codegen.ts 

<img width="521" alt="image" src="https://user-images.githubusercontent.com/11954798/218347967-35ecfda8-6045-4a69-84ab-cfd8c9fc4d3c.png">

Folder Structure
<img width="131" alt="image" src="https://user-images.githubusercontent.com/11954798/218347997-f10ff5e0-aa12-42ff-8c58-71850db60713.png">

Package.json file
<img width="713" alt="image" src="https://user-images.githubusercontent.com/11954798/218348036-55f41cde-b5e8-48cf-b316-75b5afb28a41.png">

Console Output ( No errors but no output files are generated)
<img width="184" alt="image" src="https://user-images.githubusercontent.com/11954798/218348158-a86bd114-89c8-490f-845b-36d679de354a.png">

Console with verbose 
<img width="242" alt="image" src="https://user-images.githubusercontent.com/11954798/218348590-805d1a22-d810-4404-9ee0-06d64a6df638.png">

Kindly let me know why output files are not generated

**Comment by eddeee888** [comment] 2023-02-13 08:43
Hello 👋 Can you try changing `/src/schema` to `src/schema` in your `codegen.ts`, please? :)

`/src/schema` generate the files into `/src/schema` directory
`src/schema` generates the files into `src/schema` directory relative to your current working directory

**Comment by Sandeep-Malhotra** [comment] 2023-02-13 22:17
Thanks for your reply. Still the same issue

![image](https://user-images.githubusercontent.com/11954798/218587140-c6c1aa58-eff7-46db-b1f3-0dc39fb15440.png)

**Comment by eddeee888** [comment] 2023-02-14 10:57
Do you have a repo I could clone to look at? :)

Alternatively, could you try using this forking this [Codesanbox template](https://codesandbox.io/p/sandbox/gcg-server-preset-template-4qd47b?file=%2Fsrc%2Fschema%2Fbase%2Fschema.graphql) and reproduce this bug there? 

Would be good to know the following too:

- Node version
- OS (Mac/Windows/Linux)

**Comment by Sandeep-Malhotra** [comment] 2023-02-21 01:49
> Do you have a repo I could clone to look at? :)
> 
> Alternatively, could you try using this forking this [Codesanbox template](https://codesandbox.io/p/sandbox/gcg-server-preset-95oqxn) and reproduce this bug there?
> 
> Would be good to know the following too:
> 
> * Node version
> * OS (Mac/Windows/Linux)


Thanks for your reply 

Source code link https://github.com/Sandeep-Malhotra/test-graphql-server-with-preset

**Comment by eddeee888** [comment] 2023-02-22 10:36
Hmm that's odd 🤔 I'm using your repo and it works.

![Screen Shot 2023-02-22 at 9 35 31 pm](https://user-images.githubusercontent.com/33769523/220595525-1043e912-510d-465b-8b66-86d41b819dd8.png)

---

Can you provide the following please:

- Node version
- OS (Mac/Windows/Linux)

**Comment by Sandeep-Malhotra** [comment] 2023-02-22 22:23
Below are the details
Node Version v19.6.0
OS Windows 
Running in the VS Code Git Bash Terminal
Also, I have installed NVM and its version is 1.1.9

Thanks

**Comment by eddeee888** [comment] 2023-02-26 09:53
Thank you! I know there's an issue with WIndows atm. Some people report the preset works fine with [Windows WSL](https://learn.microsoft.com/en-us/windows/wsl/install).

I'll set up a Windows machine some time this week to test. Thanks!

**Comment by Sandeep-Malhotra** [comment] 2023-02-26 22:55
Appreciate your assistance.
Thanks once again

**Comment by eddeee888** [comment] 2023-03-01 23:21
Hi @Sandeep-Malhotra, 

Can you try this alpha version that should support Windows path please:

```bash
yarn add -D @eddeee888/gcg-typescript-resolver-files@pr67-run142-1
```

Then run codegen as usual:

```
yarn graphql-codegen
```

**Comment by Sandeep-Malhotra** [comment] 2023-04-05 04:43
Sure will try and update you

**Comment by eddeee888** [comment] 2023-06-02 10:02
Looks like Windows issues have been resolved in the latest versions. I'll close this for now.
If the problem persists, please open another issue.

**Closed by eddeee888** 2023-06-02 10:02 UTC
Labels: question
