### ISSUE TITLE
[BUG] mappers for interface types on payload objects aren't generated correctly

### ISSUE THREAD

**Issue by joeyhotz** [eddeee888/graphql-code-generator-plugins#266] opened 2024-05-05 11:52 UTC
**Describe the bug**
When you have an interface type on a response payload object for a mutation, and you have a mapper for the implemented types, the types aren't generated correctly.

I have a repo here to reproduce the issue: https://github.com/joeyhotz/example-interface-type-bug-payload

**To Reproduce**
_Steps to reproduce the behavior:_
_1. `yarn`
_2. Go to src/schema/Mutation/createUser.ts

**Expected behavior**
The types generated for the mutation response should allow `{ user: { id: "123" } }` as a response for the mutation as I've defined the mappers as:
```
export type AdminUserMapper = { id: string };
export type CustomerUserMapper = { id: string };
```
It works fine for the user query.

**Additional context**
Happy to provide more context if this is not enough info. Hopefully the reproducible repo is good enough 🙏 
Thank you so much for taking a look, I'm loving the codegen plugin and really hope to see this fixed as it's blocking some nice code structures.

**Comment by nikhilgupta345** [comment] 2024-05-06 02:33
Running into this as well, would love to see a fix!

**Comment by eddeee888** [comment] 2024-05-06 09:32
Thank you! The reproducible repo is great! 

I'll take a deeper look soon 👀

**Comment by joeyhotz** [comment] 2024-05-09 04:22
yayyy
thanks for that explanation on how to run, can confirm it works in the example repo :D
thanks for fixing this :D :D

**Comment by nikhilgupta345** [comment] 2024-05-15 05:49
@eddeee888 Thanks for the fix above! I created another [repo here](https://github.com/nikhilgupta345/repro-graphql-codegen-bug) for a related bug where the mapper for the interface type itself isn't being set properly as the Resolver return type.

The way I was anticipating it would work is that (based on the example in the linked repo):
1. The `user` query returns a `User` interface type. It should expect the return value of the `UserMapper`
2. The `__resolveType` on `User.ts` should have the `UserMapper` as the parent type, and can be used to dictate which of the implementing types is being returned
3. The parent for AdminUser type resolver functions should be the AdminMapper (and similar for CustomerMapper)

Please let me know if I'm thinking about this the wrong way! The reason I would like these types is that I have a base table in my DB that maps cleanly to the interface type, but we need to fetch additional data to resolve fields on the actual object type.

**Comment by nikhilgupta345** [comment] 2024-05-16 00:58
I also noticed that if you have a type resolver for an interface, it doesn't get included in the generated `resolvers.generated.ts` file

**Comment by eddeee888** [comment] 2024-05-18 10:15
Hi @nikhilgupta345 ,

I believe your understanding is correct. Let me create another issue to track your problem.

**Comment by eddeee888** [comment] 2024-05-18 10:17
For the issue originally reported, it's been fixed in:

- `@eddeee888/gcg-typescript-resolver-files@0.8.1`
- `@graphql-codegen/typescript-resolvers@4.1.0`

**Closed by eddeee888** 2024-05-18 10:17 UTC
